name: firebase_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  get: 4.6.6
  firebase_auth: ^4.17.9
  firebase_database: ^10.4.10
  fluttertoast: 8.2.4
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.15.10
  image_picker: ^1.0.7
  firebase_storage: ^11.6.11
  firebase_messaging: ^14.8.0
  app_settings: ^5.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

