// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcj7xm_Ol-K01YohPRCS_-wFYJ0ab-vE',
    appId: '1:46415652512:web:f40817d9383d2f18394bc5',
    messagingSenderId: '46415652512',
    projectId: 'flutter-demo-44811',
    authDomain: 'flutter-demo-44811.firebaseapp.com',
    databaseURL: 'https://flutter-demo-44811-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-44811.appspot.com',
    measurementId: 'G-GH29BPCXGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_eg7KsVraqlYO_Im4qfY-YUeCSePoHOs',
    appId: '1:46415652512:android:acac7be38c0c0184394bc5',
    messagingSenderId: '46415652512',
    projectId: 'flutter-demo-44811',
    databaseURL: 'https://flutter-demo-44811-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-44811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdljPSKe1xOtqkIIYx5tiFP2FT5g-gQr8',
    appId: '1:46415652512:ios:148edd2352d158c2394bc5',
    messagingSenderId: '46415652512',
    projectId: 'flutter-demo-44811',
    databaseURL: 'https://flutter-demo-44811-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-44811.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdljPSKe1xOtqkIIYx5tiFP2FT5g-gQr8',
    appId: '1:46415652512:ios:92ab9460375d8534394bc5',
    messagingSenderId: '46415652512',
    projectId: 'flutter-demo-44811',
    databaseURL: 'https://flutter-demo-44811-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-44811.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
